"use client";

import { useState, useEffect } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { motion } from "framer-motion";
import {
  ArrowLeft, Save, Upload, X, Plus, Trash2, GripVertical,
  ImagePlus, Tag, Globe, Sparkles, Package, BarChart3, Copy, Check, Shield
} from "lucide-react";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { AdminButton } from "@/components/admin/shared/admin-button";
import { Badge } from "@/components/ui/badge";
import { Switch } from "@/components/ui/switch";
import { Separator } from "@/components/ui/separator";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Checkbox } from "@/components/ui/checkbox";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from "@/components/ui/dialog";
import { ImageUpload } from "@/components/admin/shared/image-upload";
import { ImagePositionEditor } from "@/components/admin/shared/image-position-editor";
import { FieldLabel } from "@/components/admin/shared/field-label";
import { cn } from "@/lib/utils";
import { CountrySearch } from "@/components/admin/shared/country-search";
import { BrandSearch } from "@/components/admin/shared/brand-search";
import { getIconById, type TrustBadge } from "@/lib/trust-badges";

type VariantRow = {
  id: string;
  type: "size" | "color" | "shade" | "weight";
  name: string;
  value: string;
  hex: string;
  price: string;
  compare_price: string;
  cost_price: string;
  stock: string;
  min_stock: string;
  max_stock: string;
  sku: string;
};

type ImageRow = {
  id: string;
  url: string;
  alt: string;
  variant_id: string; // "" means not linked to any variant
  focal_point: string;
};

export default function AddProductPage() {
  const router = useRouter();
  const [activeTab, setActiveTab] = useState<"basic" | "media" | "variants" | "seo">("basic");
  const [saving, setSaving] = useState(false);
  const [dbCategories, setDbCategories] = useState<{ id: string; name: string; children: { id: string; name: string; slug: string }[] }[]>([]);
  const [dbBrands, setDbBrands] = useState<{ id: string; name: string }[]>([]);
  const [brandId, setBrandId] = useState("");

  useEffect(() => {
    fetch("/api/categories")
      .then((r) => r.json())
      .then((data) => {
        if (Array.isArray(data)) {
          setDbCategories(data.map((c: Record<string, unknown>) => ({
            id: c.id as string, name: c.name as string,
            children: Array.isArray(c.children) ? (c.children as Record<string, unknown>[]).map((s) => ({ id: s.id as string, name: s.name as string, slug: s.slug as string })) : [],
          })));
        }
      })
      .catch(() => {});
    fetch("/api/brands").then((r) => r.json()).then((data) => {
      if (Array.isArray(data)) setDbBrands(data.filter((b: Record<string, unknown>) => b.is_active).map((b: Record<string, unknown>) => ({ id: b.id as string, name: b.name as string })));
    }).catch(() => {});
    fetch("/api/settings?key=trust_badges_config").then((r) => r.json()).then((data) => {
      if (data?.value && Array.isArray(data.value)) {
        setAvailableTrustBadges(data.value);
        // Default: select first 3
        if (data.value.length > 0) setSelectedTrustBadges(data.value.slice(0, 3).map((b: TrustBadge) => b.id));
      }
    }).catch(() => {});
  }, []);
  const [saved, setSaved] = useState(false);
  const [error, setError] = useState("");

  // Form state
  const [productName, setProductName] = useState("");
  const [sku, setSku] = useState("");
  const [skuAutoGenerated, setSkuAutoGenerated] = useState(true);

  const generateSku = (name: string) => {
    const prefix = name.trim().split(/\s+/).map((w) => w[0]?.toUpperCase() || "").join("").slice(0, 4);
    return `${prefix || "PRD"}-${Date.now().toString(36).toUpperCase().slice(-5)}`;
  };

  const handleNameChange = (val: string) => {
    setProductName(val);
    if (skuAutoGenerated) setSku(generateSku(val));
  };

  const handleSkuChange = (val: string) => {
    setSku(val);
    setSkuAutoGenerated(false);
  };
  const [shortDesc, setShortDesc] = useState("");
  const [fullDesc, setFullDesc] = useState("");
  const [weight, setWeight] = useState("");
  const [origin, setOrigin] = useState("");
  const [tags, setTags] = useState("");
  const [ingredients, setIngredients] = useState("");
  const [howToUse, setHowToUse] = useState("");
  const [categoryId, setCategoryId] = useState("");
  const [subcategory, setSubcategory] = useState("");
  const [selectedTrustBadges, setSelectedTrustBadges] = useState<string[]>([]);
  const [availableTrustBadges, setAvailableTrustBadges] = useState<TrustBadge[]>([]);
  const [seoTitle, setSeoTitle] = useState("");
  const [seoDesc, setSeoDesc] = useState("");
  const [seoPromptOpen, setSeoPromptOpen] = useState(false);
  const [seoPromptCopied, setSeoPromptCopied] = useState(false);
  const [isActive, setIsActive] = useState(true);

  const buildSeoPrompt = () => {
    const catName = dbCategories.find((c) => c.id === categoryId)?.name || "";
    const validVariants = variants.filter((v) => v.name && v.price);
    const prices = validVariants.map((v) => Number(v.price)).filter((p) => p > 0);
    const minPrice = prices.length > 0 ? Math.min(...prices) : 0;
    const maxPrice = prices.length > 0 ? Math.max(...prices) : 0;
    const priceDisplay = minPrice === maxPrice || prices.length <= 1 ? (minPrice ? `৳${minPrice}` : "") : `৳${minPrice} — ৳${maxPrice}`;
    const comparePrices = validVariants.map((v) => Number(v.compare_price)).filter((p) => p > 0);
    const maxCompare = comparePrices.length > 0 ? Math.max(...comparePrices) : 0;
    const discount = maxCompare > 0 && minPrice > 0 ? Math.round((1 - minPrice / maxCompare) * 100) : 0;

    const lines = [
      "You are an expert e-commerce SEO specialist. Analyze the following product details and generate:",
      "1. An SEO Title (max 60 characters)",
      "2. A Meta Description (exactly 150-160 characters)",
      "",
      "=== PRODUCT DETAILS ===",
      `Product Name: ${productName}`,
      catName ? `Category: ${catName}` : "",
      subcategory ? `Subcategory: ${subcategory}` : "",
      priceDisplay ? `Price: ${priceDisplay}` : "",
      discount > 0 ? `Discount: Up to ${discount}% off` : "",
      origin ? `Country of Origin: ${origin}` : "",
      weight ? `Weight/Size: ${weight}` : "",
      shortDesc ? `Short Description: ${shortDesc}` : "",
      fullDesc ? `Full Description: ${fullDesc}` : "",
      ingredients ? `Key Ingredients: ${ingredients}` : "",
      tags ? `Tags: ${tags}` : "",
      validVariants.length > 1 ? `Available Variants: ${validVariants.map((v) => `${v.name} (${v.type}, ৳${v.price})`).join(", ")}` : "",
      "",
      "=== STORE CONTEXT ===",
      "Store: ChineXa (chinexabd.com) — Premium beauty & lifestyle store in Bangladesh",
      "Target Audience: Women in Bangladesh looking for authentic beauty products",
      "Shipping: Free delivery on orders over ৳3,000. Cash on delivery available.",
      "USP: Authentic imported products, 7-day returns, verified genuine items",
      "",
      "=== SEO REQUIREMENTS ===",
      "- Title must include the product name and end with '| ChineXa'",
      "- Title should include a high-value keyword (e.g., origin country for imported items, key ingredient for skincare)",
      "- Description must naturally include the starting price in ৳ (BDT)",
      "- Description should mention one trust signal (free delivery / COD / authentic / genuine)",
      "- Description must be action-oriented (start with a verb like Shop, Discover, Get, Try)",
      "- Use keywords that Bangladeshi shoppers would actually search for",
      "- Do NOT use generic filler words. Every word must add SEO value.",
      "",
      "Respond in this exact format:",
      "SEO Title: [your title here]",
      "Meta Description: [your description here]",
    ];
    return lines.filter(Boolean).join("\n");
  };

  const handleCopyPrompt = () => {
    navigator.clipboard.writeText(buildSeoPrompt());
    setSeoPromptCopied(true);
    setTimeout(() => setSeoPromptCopied(false), 2000);
  };
  const [isFeatured, setIsFeatured] = useState(false);
  const [selectedBadges, setSelectedBadges] = useState<string[]>([]);
  const [variants, setVariants] = useState<VariantRow[]>([
    { id: `v-${Date.now()}`, type: "size", name: "", value: "", hex: "", price: "", compare_price: "", cost_price: "", stock: "0", min_stock: "10", max_stock: "100", sku: "" },
  ]);
  const [images, setImages] = useState<ImageRow[]>([]);

  const toggleBadge = (badge: string) => {
    setSelectedBadges((prev) =>
      prev.includes(badge) ? prev.filter((b) => b !== badge) : [...prev, badge]
    );
  };

  const addVariant = () => {
    setVariants([...variants, {
      id: `v-${Date.now()}`, type: "size", name: "", value: "", hex: "",
      price: "", compare_price: "", cost_price: "", stock: "0", min_stock: "10", max_stock: "100", sku: "",
    }]);
  };

  const removeVariant = (id: string) => {
    setVariants(variants.filter((v) => v.id !== id));
  };

  const updateVariant = (id: string, field: keyof VariantRow, value: string) => {
    setVariants(variants.map((v) => v.id === id ? { ...v, [field]: value } : v));
  };

  const addImage = () => {
    setImages([...images, { id: `img-${Date.now()}`, url: "", alt: "", variant_id: "", focal_point: "" }]);
  };

  const removeImage = (id: string) => {
    setImages(images.filter((i) => i.id !== id));
  };

  const handleSave = async () => {
    if (!productName.trim()) { setError("Product name is required"); return; }
    const firstVariant = variants[0];
    if (!firstVariant?.name.trim()) { setError("At least one variant with a name is required"); return; }
    if (!firstVariant?.price) { setError("Variant price is required"); return; }
    if (!images.some((img) => img.url)) { setError("At least 1 product image is required"); return; }
    setError("");
    setSaving(true);

    // Derive base product price/stock from first variant
    const basePrice = Number(firstVariant.price) || 0;
    const baseCostPrice = Number(firstVariant.cost_price) || 0;
    const totalStock = variants.reduce((s, v) => s + (Number(v.stock) || 0), 0);

    try {
      const payload = {
        name: productName.trim(),
        sku: sku.trim() || firstVariant.sku,
        short_description: shortDesc.trim(),
        description: fullDesc.trim(),
        price: basePrice,
        compare_at_price: firstVariant.compare_price ? Number(firstVariant.compare_price) : null,
        cost_price: baseCostPrice,
        stock_quantity: totalStock,
        min_stock: Number(firstVariant.min_stock) || 10,
        max_stock: Number(firstVariant.max_stock) || 100,
        weight: weight.trim() || null,
        country_of_origin: origin || null,
        tags: tags.split(",").map((t) => t.trim()).filter(Boolean),
        ingredients: ingredients.trim() || null,
        how_to_use: howToUse.trim() || null,
        category_id: categoryId || null,
        category_name: dbCategories.find((c) => c.id === categoryId)?.name || categoryId || null,
        subcategory: subcategory.trim() || null,
        brand_id: brandId || null,
        brand_name: dbBrands.find((b) => b.id === brandId)?.name || null,
        trust_badges: selectedTrustBadges,
        seo_title: seoTitle.trim() || null,
        seo_description: seoDesc.trim() || null,
        is_active: isActive,
        is_featured: isFeatured,
        badges: selectedBadges,
        images: images.filter((img) => img.url).map((img) => ({ url: img.url, alt: img.alt, variant_id: img.variant_id || null, focal_point: img.focal_point || null })),
        variants: variants.filter((v) => v.name).map((v) => {
          // Find the first image linked to this variant
          const linkedImg = images.find((img) => img.variant_id === v.id && img.url);
          return {
            name: v.name, type: v.type, value: v.value || v.name,
            hex: v.hex || null, price_adjustment: (Number(v.price) || 0) - basePrice,
            cost_price_adjustment: (Number(v.cost_price) || 0) - baseCostPrice,
            stock: Number(v.stock) || 0, sku: v.sku,
            image: linkedImg?.url || null, focal_point: linkedImg?.focal_point || null,
          };
        }),
      };

      const res = await fetch("/api/products", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(payload),
      });

      if (!res.ok) {
        const data = await res.json();
        throw new Error(data.error || "Failed to save product");
      }

      setSaving(false);
      setSaved(true);

      // Redirect after showing success
      setTimeout(() => {
        router.push("/admin/products");
      }, 1500);
    } catch (err: unknown) {
      setSaving(false);
      setError(err instanceof Error ? err.message : "Failed to save product");
    }
  };

  const tabs = [
    { id: "basic" as const, label: "Basic Info", icon: Package },
    { id: "variants" as const, label: "Variants & Stock", icon: Tag },
    { id: "media" as const, label: "Media", icon: ImagePlus },
    { id: "seo" as const, label: "SEO", icon: BarChart3 },
  ];

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-3">
          <Link href="/admin/products" className="flex items-center justify-center h-9 w-9 rounded-full hover:bg-pearl text-charcoal-lighter hover:text-charcoal transition-colors">
            <ArrowLeft className="h-4 w-4" />
          </Link>
          <div>
            <h1 className="font-heading text-2xl font-semibold text-charcoal">Add Product</h1>
            <p className="text-xs text-charcoal-lighter">Create a new product listing</p>
          </div>
        </div>
        <div className="flex items-center gap-2">
          <AdminButton size="sm" onClick={handleSave} disabled={saving} className={saved ? "!bg-success hover:!bg-success" : ""}>
            <Save className="h-3.5 w-3.5" /> {saving ? "Saving..." : saved ? "Saved!" : "Save Product"}
          </AdminButton>
        </div>
      </div>

      {/* Alerts */}
      {saved && (
        <motion.div initial={{ opacity: 0, y: -10 }} animate={{ opacity: 1, y: 0 }}
          className="flex items-center gap-2 p-3 rounded-xl bg-success/10 border border-success/20 text-success text-sm font-medium">
          <Save className="h-4 w-4" /> Product saved successfully! Redirecting to product list...
        </motion.div>
      )}
      {error && (
        <motion.div initial={{ opacity: 0, y: -10 }} animate={{ opacity: 1, y: 0 }}
          className="flex items-center gap-2 p-3 rounded-xl bg-destructive/10 border border-destructive/20 text-destructive text-sm font-medium">
          <X className="h-4 w-4" /> {error}
        </motion.div>
      )}

      {/* Tab Navigation */}
      <div className="flex gap-1 bg-pearl/60 p-1 rounded-xl overflow-x-auto scrollbar-hide">
        {tabs.map((tab) => (
          <button
            key={tab.id}
            onClick={() => setActiveTab(tab.id)}
            className={cn(
              "flex items-center gap-1.5 sm:gap-2 px-2.5 sm:px-4 py-2.5 rounded-lg text-xs sm:text-sm font-medium whitespace-nowrap shrink-0 transition-all duration-200",
              activeTab === tab.id
                ? "bg-white text-charcoal shadow-card"
                : "text-charcoal-lighter hover:text-charcoal"
            )}
          >
            <tab.icon className="h-4 w-4 shrink-0" /> {tab.label}
          </button>
        ))}
      </div>

      <div className="grid lg:grid-cols-3 gap-6">
        {/* ═══ Main Content ═══ */}
        <div className="lg:col-span-2 space-y-6">
          {/* Basic Info */}
          {activeTab === "basic" && (
            <motion.div initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} className="space-y-6">
              <Card>
                <CardHeader>
                  <CardTitle className="text-base">Product Information</CardTitle>
                  <CardDescription>Basic details about the product</CardDescription>
                </CardHeader>
                <CardContent className="space-y-4">
                  <Input label="Product Name" placeholder="e.g., CosRX Vitamin C Brightening Serum" value={productName} onChange={(e) => handleNameChange(e.target.value)} />
                  <Input label={<FieldLabel label="SKU" hint="Auto-generated from the product name — edit if you need a specific code." />} placeholder="Auto-generated from name" value={sku} onChange={(e) => handleSkuChange(e.target.value)} />
                  <Textarea label="Short Description" placeholder="Brief 1-2 sentence description..." className="min-h-[80px]" value={shortDesc} onChange={(e) => setShortDesc(e.target.value)} />
                  <Textarea label="Full Description" placeholder="Detailed product description..." className="min-h-[150px]" value={fullDesc} onChange={(e) => setFullDesc(e.target.value)} />
                </CardContent>
              </Card>

              <Card>
                <CardHeader>
                  <CardTitle className="text-base flex items-center gap-2">
                    <Globe className="h-4 w-4 text-secondary" /> Origin & Details
                  </CardTitle>
                </CardHeader>
                <CardContent className="space-y-4">
                  <div className="grid sm:grid-cols-2 gap-4">
                    <CountrySearch value={origin} onChange={setOrigin} />
                    <Input label={<FieldLabel label="Tags" hint="Comma separated — used for search and filtering." />} placeholder="skincare, serum, vitamin-c" value={tags} onChange={(e) => setTags(e.target.value)} />
                  </div>
                  <Textarea label="Ingredients" placeholder="Water, Glycerin, Niacinamide..." className="min-h-[80px]" value={ingredients} onChange={(e) => setIngredients(e.target.value)} />
                  <Textarea label="How to Use" placeholder="Apply to cleansed skin morning and evening..." className="min-h-[80px]" value={howToUse} onChange={(e) => setHowToUse(e.target.value)} />
                </CardContent>
              </Card>
            </motion.div>
          )}

          {/* Variants, Media & Stock */}
          {activeTab === "variants" && (
            <motion.div initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} className="space-y-6">
              <Card>
                <CardHeader className="flex-row items-center justify-between space-y-0">
                  <div>
                    <CardTitle className="text-base">Product Variants</CardTitle>
                    <CardDescription>Add size, color, or other variations</CardDescription>
                  </div>
                  <button
                    onClick={addVariant}
                    className="inline-flex items-center gap-1.5 h-9 px-4 rounded-full bg-secondary text-white text-[12px] font-body font-semibold tracking-wide hover:bg-secondary-dark hover:shadow-[0_6px_30px_rgba(122,79,160,0.4)] hover:-translate-y-[1px] active:scale-[0.96] transition-all duration-300 cursor-pointer"
                  >
                    <Plus className="h-3.5 w-3.5" /> Add Variant
                  </button>
                </CardHeader>
                <CardContent>
                    <div className="space-y-4">
                      {variants.map((variant, i) => (
                        <div key={variant.id} className="rounded-xl border border-border/30 overflow-hidden">
                          <div className="flex items-center justify-between px-4 py-2.5 bg-pearl/50 border-b border-border/20">
                            <span className="text-xs font-bold text-charcoal">Variant {i + 1} {i === 0 && <span className="text-[9px] text-secondary font-normal ml-1">(default)</span>}</span>
                            {variants.length > 1 && (
                              <button onClick={() => removeVariant(variant.id)} className="p-1 rounded-full hover:bg-destructive/10 text-charcoal-lighter hover:text-destructive transition-colors">
                                <Trash2 className="h-3.5 w-3.5" />
                              </button>
                            )}
                          </div>

                          <div className="p-4 space-y-4">
                            {/* Variant Info */}
                            <div>
                              <p className="text-[10px] font-semibold text-charcoal-lighter uppercase tracking-wider mb-2">Variant Info</p>
                              <div className="grid sm:grid-cols-3 gap-3">
                                <Select value={variant.type} onValueChange={(v) => updateVariant(variant.id, "type", v)}>
                                  <SelectTrigger><SelectValue placeholder="Type" /></SelectTrigger>
                                  <SelectContent>
                                    <SelectItem value="size">Size</SelectItem>
                                    <SelectItem value="color">Color</SelectItem>
                                    <SelectItem value="shade">Shade</SelectItem>
                                    <SelectItem value="weight">Weight</SelectItem>
                                  </SelectContent>
                                </Select>
                                <Input placeholder="Name * (e.g., 50ml, Red)" value={variant.name} onChange={(e) => updateVariant(variant.id, "name", e.target.value)} />
                                <Input placeholder="Display Value" value={variant.value} onChange={(e) => updateVariant(variant.id, "value", e.target.value)} />
                              </div>
                              {variant.type === "color" && (
                                <div className="flex items-center gap-2 mt-2">
                                  <input type="color" value={variant.hex || "#C0392B"} onChange={(e) => updateVariant(variant.id, "hex", e.target.value)} className="h-9 w-9 rounded-lg border border-border cursor-pointer" />
                                  <span className="text-xs text-charcoal-lighter font-mono">{variant.hex || "#C0392B"}</span>
                                </div>
                              )}
                            </div>

                            {/* Pricing */}
                            <div>
                              <p className="text-[10px] font-semibold text-charcoal-lighter uppercase tracking-wider mb-2">Pricing</p>
                              <div className="grid sm:grid-cols-2 gap-3">
                                <Input label="Price (৳) *" placeholder="2500" type="number" value={variant.price} onChange={(e) => updateVariant(variant.id, "price", e.target.value)} />
                                <Input label="Compare at Price (৳)" placeholder="3200 (optional, for sale badge)" type="number" value={variant.compare_price} onChange={(e) => updateVariant(variant.id, "compare_price", e.target.value)} />
                              </div>
                              <div className="grid sm:grid-cols-2 gap-3 mt-3">
                                <Input label="Cost Price (৳)" placeholder="1200 (optional, for profit tracking)" type="number" value={variant.cost_price} onChange={(e) => updateVariant(variant.id, "cost_price", e.target.value)} />
                                {variant.price && variant.cost_price && Number(variant.price) > 0 && (
                                  <div className="flex items-end pb-2">
                                    <span className="text-xs text-charcoal-lighter">
                                      Margin: <span className="font-semibold text-secondary">{(((Number(variant.price) - Number(variant.cost_price)) / Number(variant.price)) * 100).toFixed(1)}%</span>
                                    </span>
                                  </div>
                                )}
                              </div>
                            </div>

                            {/* Inventory */}
                            <div>
                              <p className="text-[10px] font-semibold text-charcoal-lighter uppercase tracking-wider mb-2">Inventory</p>
                              <div className="grid sm:grid-cols-2 gap-3">
                                <Input label="SKU" placeholder="e.g., SK-0001-50ML" value={variant.sku} onChange={(e) => updateVariant(variant.id, "sku", e.target.value)} />
                                <Input label="Stock Quantity" placeholder="0" type="number" value={variant.stock} onChange={(e) => updateVariant(variant.id, "stock", e.target.value)} />
                              </div>
                              <div className="grid sm:grid-cols-2 gap-3 mt-3">
                                <Input label={<FieldLabel label="Min Stock" hint="Triggers a low-stock alert once inventory falls to or below this number." />} placeholder="10" type="number" value={variant.min_stock} onChange={(e) => updateVariant(variant.id, "min_stock", e.target.value)} />
                                <Input label={<FieldLabel label="Max Stock" hint="Triggers an overstock alert once inventory exceeds this number." />} placeholder="100" type="number" value={variant.max_stock} onChange={(e) => updateVariant(variant.id, "max_stock", e.target.value)} />
                              </div>
                            </div>

                          </div>
                        </div>
                      ))}
                    </div>
                </CardContent>
              </Card>
            </motion.div>
          )}

          {/* Media */}
          {activeTab === "media" && (
            <motion.div initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} className="space-y-6">
              <Card>
                <CardHeader>
                  <CardTitle className="text-base">Product Images</CardTitle>
                  <CardDescription>Add images and optionally link them to a variant. First image is the main display image.</CardDescription>
                </CardHeader>
                <CardContent>
                  <div className="space-y-4">
                    {images.map((img, i) => (
                      <div key={img.id} className="p-4 rounded-xl border border-border/30 bg-pearl/20">
                        <div className="flex items-center justify-between mb-3">
                          <span className="text-xs font-bold text-charcoal">Image {i + 1} {i === 0 && <span className="text-[9px] text-secondary font-normal ml-1">(main)</span>}</span>
                          <button onClick={() => removeImage(img.id)} className="p-1 rounded-full hover:bg-destructive/10 text-charcoal-lighter hover:text-destructive transition-colors">
                            <Trash2 className="h-3.5 w-3.5" />
                          </button>
                        </div>
                        <div className="grid sm:grid-cols-2 gap-4">
                          <ImageUpload
                            value={img.url}
                            onChange={(url) => { const u = [...images]; u[i].url = url; setImages(u); }}
                            aspectRatio="square"
                            productId={`prod-new`}
                            imageIndex={String(i).padStart(4, "0")}
                          />
                          <div className="space-y-3">
                            <Input label="Alt Text" placeholder="Describe the image" value={img.alt} onChange={(e) => { const u = [...images]; u[i].alt = e.target.value; setImages(u); }} />
                            <div>
                              <label className="block text-sm font-medium text-charcoal-light mb-1.5"><FieldLabel label="Link to Variant" hint="When a customer selects this variant, this image will be shown." /></label>
                              <Select value={img.variant_id} onValueChange={(v) => { const u = [...images]; u[i].variant_id = v; setImages(u); }}>
                                <SelectTrigger><SelectValue placeholder="No variant (general image)" /></SelectTrigger>
                                <SelectContent>
                                  <SelectItem value="">No variant (general image)</SelectItem>
                                  {variants.filter((v) => v.name).map((v) => (
                                    <SelectItem key={v.id} value={v.id}>{v.name} ({v.type})</SelectItem>
                                  ))}
                                </SelectContent>
                              </Select>
                            </div>
                            {img.url && (
                              <ImagePositionEditor
                                imageUrl={img.url}
                                value={img.focal_point}
                                onChange={(val) => { const u = [...images]; u[i].focal_point = val; setImages(u); }}
                                aspectRatio="square"
                              />
                            )}
                          </div>
                        </div>
                      </div>
                    ))}

                    {images.length < 8 && (
                      <button onClick={addImage}
                        className="w-full py-6 rounded-xl border-2 border-dashed border-border/40 hover:border-secondary/40 hover:bg-primary-light/20 transition-all flex items-center justify-center gap-2 text-charcoal-lighter hover:text-secondary">
                        <Plus className="h-5 w-5" /> <span className="text-sm font-medium">Add Image</span>
                      </button>
                    )}
                  </div>
                </CardContent>
              </Card>
            </motion.div>
          )}

          {/* SEO */}
          {activeTab === "seo" && (
            <motion.div initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} className="space-y-6">
              {/* Trust Badges */}
              <Card>
                <CardHeader>
                  <div className="flex items-center justify-between">
                    <div>
                      <CardTitle className="text-base flex items-center gap-2"><Shield className="h-4 w-4 text-secondary" /> <FieldLabel label="Trust Badges" hint="Select up to 3 badges to display on this product's page." /></CardTitle>
                      <CardDescription><a href="/admin/trust-badges" target="_blank" className="text-secondary hover:underline">Manage badges</a></CardDescription>
                    </div>
                  </div>
                </CardHeader>
                <CardContent>
                  {availableTrustBadges.length === 0 ? (
                    <p className="text-xs text-charcoal-lighter text-center py-4">No trust badges configured. <a href="/admin/trust-badges" className="text-secondary hover:underline">Create some</a></p>
                  ) : (
                  <div className="grid grid-cols-2 sm:grid-cols-3 gap-2">
                    {availableTrustBadges.map((badge) => {
                      const isSelected = selectedTrustBadges.includes(badge.id);
                      const Icon = getIconById(badge.icon);
                      return (
                        <button
                          key={badge.id}
                          type="button"
                          onClick={() => {
                            if (isSelected) setSelectedTrustBadges((prev) => prev.filter((b) => b !== badge.id));
                            else if (selectedTrustBadges.length < 3) setSelectedTrustBadges((prev) => [...prev, badge.id]);
                          }}
                          disabled={!isSelected && selectedTrustBadges.length >= 3}
                          className={cn(
                            "flex items-center gap-2 p-3 rounded-xl border text-left transition-all",
                            isSelected ? "border-secondary bg-secondary/5" : "border-border/30 hover:border-secondary/40",
                            !isSelected && selectedTrustBadges.length >= 3 && "opacity-40 cursor-not-allowed"
                          )}
                        >
                          <Icon className="h-4 w-4 text-secondary shrink-0" />
                          <div>
                            <p className="text-xs font-medium text-charcoal">{badge.title}</p>
                            <p className="text-[9px] text-charcoal-lighter">{badge.description}</p>
                          </div>
                        </button>
                      );
                    })}
                  </div>
                  )}
                  <p className="text-[10px] text-charcoal-lighter mt-2">{selectedTrustBadges.length}/3 selected</p>
                </CardContent>
              </Card>

              <Card>
                <CardHeader>
                  <CardTitle className="text-base flex items-center gap-2">
                    <BarChart3 className="h-4 w-4 text-secondary" /> Search Engine Optimization
                  </CardTitle>
                  <CardDescription>Optimize how this product appears in search results</CardDescription>
                </CardHeader>
                <CardContent className="space-y-4">
                  <div className="flex items-center justify-between">
                    <p className="text-xs text-charcoal-lighter">Paste from ChatGPT / Gemini, or write manually</p>
                    <button type="button" onClick={() => setSeoPromptOpen(true)} className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-secondary/10 text-secondary text-[11px] font-medium hover:bg-secondary/20 transition-colors">
                      <Copy className="h-3 w-3" /> Copy for AI
                    </button>
                  </div>
                  <Input label="SEO Title" placeholder="Product name — Key Detail | ChineXa" value={seoTitle} onChange={(e) => setSeoTitle(e.target.value)} />
                  <div>
                    <Textarea label="Meta Description" placeholder="A compelling description for search results..." className="min-h-[80px]" value={seoDesc} onChange={(e) => setSeoDesc(e.target.value)} />
                    <p className={cn("text-[10px] mt-1 text-right", seoDesc.length === 0 ? "text-charcoal-lighter" : seoDesc.length >= 150 && seoDesc.length <= 160 ? "text-success font-medium" : seoDesc.length > 160 ? "text-destructive" : "text-warning")}>
                      {seoDesc.length}/160 chars {seoDesc.length >= 150 && seoDesc.length <= 160 ? "— Perfect!" : seoDesc.length > 160 ? "— Too long" : seoDesc.length > 0 ? "— Aim for 150-160" : ""}
                    </p>
                  </div>

                  <Separator />

                  {/* Live Search Preview */}
                  <div>
                    <p className="text-xs font-semibold text-charcoal-lighter uppercase tracking-wider mb-2">Google Search Preview</p>
                    <div className="p-4 rounded-xl border border-border/30 bg-white">
                      <p className="text-blue-600 text-base font-medium truncate">{seoTitle || productName || "Product Name"} {!seoTitle && !productName ? "— ChineXa" : ""}</p>
                      <p className="text-green-700 text-xs">chinexabd.com/products/{productName ? productName.toLowerCase().replace(/[^\w\s-]/g, "").replace(/[\s_-]+/g, "-").replace(/^-+|-+$/g, "") : "product-slug"}</p>
                      <p className="text-sm text-charcoal-light mt-1 line-clamp-2">
                        {seoDesc || shortDesc || "Your meta description will appear here..."}
                      </p>
                    </div>
                  </div>
                </CardContent>
              </Card>
            </motion.div>
          )}
        </div>

        {/* ═══ Sidebar ═══ */}
        <div className="space-y-5">
          {/* Status */}
          <Card>
            <CardHeader className="pb-3">
              <CardTitle className="text-sm">Status</CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
              <div className="flex items-center justify-between">
                <p className="text-sm font-medium text-charcoal"><FieldLabel label="Active" hint="Visible on the storefront." /></p>
                <Switch checked={isActive} onCheckedChange={setIsActive} />
              </div>
              <div className="flex items-center justify-between">
                <p className="text-sm font-medium text-charcoal"><FieldLabel label="Featured" hint="Shown in featured/homepage product sections." /></p>
                <Switch checked={isFeatured} onCheckedChange={setIsFeatured} />
              </div>
            </CardContent>
          </Card>

          {/* Category */}
          <Card>
            <CardHeader className="pb-3">
              <CardTitle className="text-sm">Category</CardTitle>
            </CardHeader>
            <CardContent className="space-y-3">
              <Select value={categoryId} onValueChange={(v) => { setCategoryId(v); setSubcategory(""); }}>
                <SelectTrigger><SelectValue placeholder="Select category" /></SelectTrigger>
                <SelectContent>
                  {dbCategories.length > 0 ? (
                    dbCategories.map((cat) => (
                      <SelectItem key={cat.id} value={cat.id}>{cat.name}</SelectItem>
                    ))
                  ) : (
                    <SelectItem value="" disabled>No categories — add one first</SelectItem>
                  )}
                </SelectContent>
              </Select>
              {(() => {
                const subs = dbCategories.find((c) => c.id === categoryId)?.children || [];
                return subs.length > 0 ? (
                  <Select value={subcategory} onValueChange={setSubcategory}>
                    <SelectTrigger><SelectValue placeholder="Subcategory (optional)" /></SelectTrigger>
                    <SelectContent>
                      <SelectItem value="">None</SelectItem>
                      {subs.map((s) => <SelectItem key={s.id} value={s.name}>{s.name}</SelectItem>)}
                    </SelectContent>
                  </Select>
                ) : null;
              })()}
              {/* Brand */}
              <BrandSearch brands={dbBrands} value={brandId} onChange={setBrandId} />
            </CardContent>
          </Card>

          {/* Badges */}
          <Card>
            <CardHeader className="pb-3">
              <CardTitle className="text-sm flex items-center gap-1.5">
                <Sparkles className="h-3.5 w-3.5 text-secondary" /> Badges
              </CardTitle>
            </CardHeader>
            <CardContent>
              <div className="flex flex-wrap gap-2">
                {["new", "sale", "bestseller", "preorder", "limited", "trending"].map((badge) => (
                  <button
                    key={badge}
                    onClick={() => toggleBadge(badge)}
                    className={cn(
                      "px-3 py-1.5 rounded-full text-xs font-medium border transition-all duration-200 capitalize",
                      selectedBadges.includes(badge)
                        ? "bg-secondary text-white border-secondary"
                        : "bg-white text-charcoal-lighter border-border hover:border-charcoal hover:text-charcoal"
                    )}
                  >
                    {badge === "preorder" ? "Pre-order" : badge}
                  </button>
                ))}
              </div>
            </CardContent>
          </Card>

          {/* Quick Tips */}
          <Card className="bg-primary-light/50 border-0">
            <CardContent className="p-4">
              <p className="text-xs font-semibold text-charcoal mb-2 flex items-center gap-1.5">
                <Sparkles className="h-3.5 w-3.5 text-secondary" /> Tips
              </p>
              <ul className="text-[11px] text-charcoal-light space-y-1.5 leading-relaxed">
                <li>• Use high-quality images (min 600x750px)</li>
                <li>• Write unique descriptions for better SEO</li>
                <li>• Add at least 4 product images</li>
                <li>• Include ingredients for skincare products</li>
                <li>• Set compare price for sale badges</li>
              </ul>
            </CardContent>
          </Card>
        </div>
      </div>

      {/* SEO Prompt Modal */}
      <Dialog open={seoPromptOpen} onOpenChange={setSeoPromptOpen}>
        <DialogContent className="w-[95vw] max-w-lg max-h-[90vh] flex flex-col overflow-hidden">
          <DialogHeader className="shrink-0">
            <DialogTitle className="flex items-center gap-2"><Sparkles className="h-5 w-5 text-secondary" /> AI SEO Prompt</DialogTitle>
            <DialogDescription>Copy this prompt and paste it in ChatGPT, Gemini, or Claude to generate SEO title &amp; description</DialogDescription>
          </DialogHeader>
          <div className="flex-1 overflow-y-auto py-2">
            <pre className="whitespace-pre-wrap text-xs text-charcoal bg-pearl/60 rounded-xl p-4 border border-border/30 font-mono leading-relaxed select-all">
              {buildSeoPrompt()}
            </pre>
          </div>
          <div className="flex justify-end gap-2 pt-2 shrink-0">
            <button onClick={() => setSeoPromptOpen(false)} className="px-4 py-2 text-xs text-charcoal-lighter hover:text-charcoal transition-colors">Close</button>
            <button onClick={handleCopyPrompt} className={cn("flex items-center gap-1.5 px-4 py-2 rounded-lg text-xs font-medium transition-all", seoPromptCopied ? "bg-success text-white" : "bg-secondary text-white hover:bg-secondary-dark")}>
              {seoPromptCopied ? <><Check className="h-3 w-3" /> Copied!</> : <><Copy className="h-3 w-3" /> Copy Prompt</>}
            </button>
          </div>
        </DialogContent>
      </Dialog>
    </div>
  );
}
